spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: cloud-gateway
          uri: lb://cloud-gateway
          predicates:
            - Path=/departments/**

server:
  port: 9191
